export const seedUsers = [
  {
    name: 'HelpHive Admin',
    email: 'admin@helphive.org',
    password: 'Admin@123',
    role: 'admin',
    status: 'approved',
    location: 'Delhi',
    skills: ['Operations', 'Coordination'],
  },
  {
    name: 'Rahul',
    email: 'aarav@example.com',
    password: 'Volunteer@123',
    role: 'volunteer',
    status: 'approved',
    location: 'Delhi',
    skills: ['Medical', 'First Aid'],
    availability: true,
    hoursContributed: 126,
    impactScore: 92,
    eventsJoined: 8,
    coordinates: { lat: 28.6139, lng: 77.209 },
  },
  {
    name: 'Aisha',
    email: 'meera@example.com',
    password: 'Volunteer@123',
    role: 'volunteer',
    status: 'approved',
    dutyStatus: 'off-duty',
    location: 'Bengaluru',
    skills: ['Coordination', 'Nearby Response'],
    availability: true,
    hoursContributed: 148,
    impactScore: 96,
    eventsJoined: 11,
    coordinates: { lat: 12.9716, lng: 77.5946 },
  },
  {
    name: 'Kiran',
    email: 'kiran@example.com',
    password: 'Volunteer@123',
    role: 'volunteer',
    status: 'approved',
    dutyStatus: 'on-duty',
    location: 'Jaipur',
    skills: ['Logistics', 'Supply Chain'],
    availability: true,
    hoursContributed: 102,
    impactScore: 88,
    eventsJoined: 6,
    coordinates: { lat: 26.9124, lng: 75.7873 },
  },
];

export const seedEvents = [
  {
    title: 'Flood Relief Camp',
    date: new Date(),
    location: 'Delhi NCR',
    description: 'Distribution of essentials to urban shelters',
    resourcesRequired: [
      { resourceName: 'Food Kits', quantity: 200 },
      { resourceName: 'Medical Packs', quantity: 60 },
      { resourceName: 'Water Units', quantity: 120 },
    ],
    status: 'active',
    coordinates: { lat: 28.7041, lng: 77.1025 },
  },
  {
    title: 'Rural Health Camp',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    location: 'Jaipur',
    description: 'Medical checkup and medicine distribution camp',
    resourcesRequired: [
      { resourceName: 'Medical Packs', quantity: 90 },
      { resourceName: 'Water Units', quantity: 70 },
    ],
    status: 'planned',
    coordinates: { lat: 26.9124, lng: 75.7873 },
  },
];

export const seedResources = [
  { resourceName: 'Food Kits', quantity: 320, location: 'Delhi Warehouse', status: 'available' },
  { resourceName: 'Medical Packs', quantity: 75, location: 'Jaipur Hub', status: 'low' },
  { resourceName: 'Water Units', quantity: 22, location: 'Central Depot', status: 'critical' },
];
